aerial_robot_control_name: aerial_robot_control/under_actuated_controller

controller:
  xy:
    p_gain: 2.5
    i_gain: 0.05
    d_gain: 1.5
    limit_sum: 3
    limit_p: 3
    limit_i: 1.5
    limit_d: 3

  z:
    p_gain: 5.0
    i_gain: 2.5
    d_gain: 5.0
    limit_err_p: 1.0
    limit_sum: 10 # N for clamping thrust force
    limit_p: 20 # m / s^2
    limit_i: 40 # m / s^2
    limit_d: 20 # m / s^2
    landing_err_z: -0.2
    force_landing_descending_rate: -0.6

  roll_pitch:
    p_gain: 15
    i_gain: 0.3
    d_gain: 5 # 5: good, 7: deverge in the takeoff phase
    limit_sum: 10
    limit_p: 10
    limit_i: 10
    limit_d: 10

  yaw:
    limit_sum: 6.0 # N for clamping thrust force
    limit_p: 4.0
    limit_i: 4.0
    limit_d: 4.0
    limit_err_p: 0.4
    need_d_control: false